-- MySQL Script generated by MySQL Workbench
-- Thu Apr  4 22:20:09 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema aulajava
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema aulajava
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `aulajava` DEFAULT CHARACTER SET utf8 ;
USE `aulajava` ;

-- -----------------------------------------------------
-- Table `aulajava`.`menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aulajava`.`menu` (
  `idMenu` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `link` VARCHAR(100) NOT NULL,
  `icone` VARCHAR(45) NULL,
  `exibir` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idMenu`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aulajava`.`Perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aulajava`.`Perfil` (
  `idPerfil` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPerfil`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aulajava`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aulajava`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `login` VARCHAR(10) NOT NULL,
  `senha` VARCHAR(10) NOT NULL,
  `status` INT NOT NULL,
  `idPerfil` INT NOT NULL,
  PRIMARY KEY (`idusuario`),
  INDEX `fk_usuario_Perfil1_idx` (`idPerfil` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_Perfil1`
    FOREIGN KEY (`idPerfil`)
    REFERENCES `aulajava`.`Perfil` (`idPerfil`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aulajava`.`menu_Perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aulajava`.`menu_Perfil` (
  `idMenu` INT NOT NULL,
  `idPerfil` INT NOT NULL,
  PRIMARY KEY (`idMenu`, `idPerfil`),
  INDEX `fk_menu_has_Perfil_Perfil1_idx` (`idPerfil` ASC) VISIBLE,
  INDEX `fk_menu_has_Perfil_menu_idx` (`idMenu` ASC) VISIBLE,
  CONSTRAINT `fk_menu_has_Perfil_menu`
    FOREIGN KEY (`idMenu`)
    REFERENCES `aulajava`.`menu` (`idMenu`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_menu_has_Perfil_Perfil1`
    FOREIGN KEY (`idPerfil`)
    REFERENCES `aulajava`.`Perfil` (`idPerfil`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
